server:
  basePath: /v1
  addr: :8080
  startTimeout: 15s
database:
  url: root:ethanli-dev123456@tcp(127.0.0.1:3306)/ethanli-dev?charset=utf8mb4&parseTime=True&loc=Local
tenant:
  aes_key: y3v8k2RqZ9LpXcB7WmNwDtGxHjMfKsQ6