definitions:
  api.Response-any:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      timestamp:
        type: integer
    type: object
  v1.TenantRequest:
    properties:
      description:
        description: tenant description
        type: string
      name:
        description: tenant name
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server celler server.
  title: Go App Layout API
  version: "1.0"
paths:
  /tenant/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create tenant request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/v1.TenantRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Create tenant response
          schema:
            $ref: '#/definitions/api.Response-any'
      summary: Create tenant
      tags:
      - tenant
swagger: "2.0"
